name: Build and Push Docker Image

# 手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Docker Buildx 环境（支持高级构建特性）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/genspark2api:latest .

      # 5. 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/genspark2api:latest
